### ISSUE TITLE
Bus vs No Bus Usage Question

### ISSUE THREAD

**Issue by dqdinh** [milankinen/react-bacon-todomvc#1]
What your thoughts are the benefits of using of a bus cache in the Dispatcher and the general RX advice against using Buses/Subjects (http://baconjs.blogspot.com/2014/12/bus-of-doom.html)[1]?

At the moment, I don't see a problem with the use of a bus if it is restricted to the bus cache in a dispatcher and kept out of the business logic. Drawing from the baconjs blog post[1], if one were to implement this todomvc app without buses, one alternative would be to create specific actions streams ('remove', ect.,), cache them in a stream cache in place of the bus cache, and call the stream as presented currently in `todo.toItemsProperty()`. It is not immediately clear to me what benefits are gained by eliminating buses in this todomvc example. I can't think of a situation where the dispatcher could potentially create a bug. Maybe this case is an exception to the 'avoid buses' rule.

Let me know what you think. Thanks.

**Comment by milankinen** [comment]
Hi @dqdinh and sorry for delayed answer. I completely missed this issue... Sorry about that.

Yeah I know that Buses/Subjects are considered as bad practice in FRP but in React's case they are unfortunately the only way create actions from UI. The reason is that event streams must be known when building the application state ("addItem", "remove", ...) but the UI is instantiated ad hoc ("add item" button may not be visible during the first render). 

Thus the following circular dependency is introduced:

```
<app-state> ---depends on---> <ui-action-streams> ---depend on---> <app-state> 
```

The break this circular dependency, `<ui-action-streams>` must be created before `<app-state>`. And because action streams are created _before_ the UI, there is no chance to emit events into them (due to immutable characteristics of EventStreams) unless they are buses/subjects. Thus, buses/subjects seem to be the only option for now..

I you have an implementation with FRP & React without using buses/subjects, I'd gladly look at it and get some inspiration how to do this "better". :-) 

I've created (yet another) Flux library that hides the ugly implementation details of buses/subjects and focuses on functions and event streams instead. You can take a look at it: https://github.com/milankinen/ffux

**Comment by dqdinh** [comment]
thanks
